Desafio-13/articulo/urls.py
from django.urls import path
from .views import  ArtCreateView, AllArticlesView, AllCategoriaView,AllCategoriaArticlesView, CategoryCreateView, CategoryDeleteView, ArtDetailView, ArtUpdateView, ArtDeleteView, AllAboutView, AllContactView

app_name="articulos"

urlpatterns = [

    path('create/', ArtCreateView.as_view(), name="article_create"),

    path('all-articles/', AllArticlesView.as_view(), name="all_articles"),

    path('all-category/', AllCategoriaView.as_view(), name="all_category"),

    path('category/<int:category_id>/', AllCategoriaArticlesView.as_view(), name='all_category_articles'),

    path('create-category/', CategoryCreateView.as_view(), name="create_category"),

    path('<int:pk>/delete-category/', CategoryDeleteView.as_view(), name="delete_category"),

    path('Article/<int:post_id>/', ArtDetailView.as_view(), name="detail_article"),

    path('<int:pk>/update/', ArtUpdateView.as_view(), name="update_article"),

    path('<int:pk>/delete-article/', ArtDeleteView.as_view(), name="delete_article"),

    path('about/', AllAboutView.as_view(), name="about"),

    path('contac/', AllContactView.as_view(), name="contact")
]

Desafio-13/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from .views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name="home"),
    path('accounts/', include('usuarios.urls')),
    path('articles/', include('articulo.urls')),
    path('comentarios/', include('comentarios.urls')),
    path('contacto/', include('contacto.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Desafio-13/usuarios/urls.py
from .views import CustomPasswordResetView, CustomPasswordResetDoneView, CustomPasswordResetConfirmView, CustomPasswordResetCompleteView
from django.urls import path
from .views import *
from . import views

app_name="usuarios"

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login_user'), 
    path('signup/', CustomRegisterUserView.as_view(), {'next_page': None}, name='signup_user'),  
    path('logout/', CustomLogoutView.as_view(), name='logout_user'),  
    path('confirm_logout/', CustomConfirmLogoutView.as_view(), {'next_page': None}, name='confirm_logout_user'),

    path('author/<int:pk>/', views.AuthorDetailView.as_view(), name='author_detail'),

    path('update/', CustomUpdateUserView.as_view(), name='update_user'),
    path('change_password/', CustomPasswordChangeView.as_view(), name='change_password'),

    path('password_reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

Desafio-13/templates/partials/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand fw-bold fst-italic" href="/">WEBSITE RED DE SALUD</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'articulos:all_articles'%}">Articulos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'articulos:all_category'%}">Categorías</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active " href="{% url 'articulos:about'%}">Acerca de</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'articulos:contact'%}">Contacto</a>
                </li>

                {% if user.is_authenticated %}
                    <!-- Menú desplegable "Mi Perfil" -->
                    <li class="nav-item dropdown">
                        <a class="nav-link active dropdown-toggle" href="#" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                            <img src="{{ user.image.url }}" alt="Mi Perfil" class="profile-image">
                            Perfil
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                            <li><a class="dropdown-item" href="{% url 'usuarios:update_user' %}">Ver Perfil</a></li>
                            {% if user.is_colaborador %}
                            <li><a class="dropdown-item" href="{% url 'articulos:article_create' %}">Publicar Articulos</a></li>
                            {% endif %}
                            <li><a class="dropdown-item" href="{% url 'usuarios:confirm_logout_user' %}?next={{path}}">Cerrar sesión</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a href="{% url 'usuarios:login_user' %}" class="nav-link">Iniciar sesión</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'usuarios:signup_user' %}" class="nav-link">Registrarse</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

  