Desafio-13/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from .views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name="home"),
    path('accounts/', include('usuarios.urls')),
    path('articles/', include('articulo.urls')),
    path('comentarios/', include('comentarios.urls')),
    path('contacto/', include('contacto.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Desafio-13/usuarios/urls.py
from .views import CustomPasswordResetView, CustomPasswordResetDoneView, CustomPasswordResetConfirmView, CustomPasswordResetCompleteView
from django.urls import path
from .views import *
from . import views

app_name="usuarios"

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login_user'), 
    path('signup/', CustomRegisterUserView.as_view(), {'next_page': None}, name='signup_user'),  
    path('logout/', CustomLogoutView.as_view(), name='logout_user'),  
    path('confirm_logout/', CustomConfirmLogoutView.as_view(), {'next_page': None}, name='confirm_logout_user'),

    path('author/<int:pk>/', views.AuthorDetailView.as_view(), name='author_detail'),

    path('update/', CustomUpdateUserView.as_view(), name='update_user'),
    path('change_password/', CustomPasswordChangeView.as_view(), name='change_password'),

    path('password_reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

Desafio-13/templates/data/data_user/confirm_logout.html
{% extends 'layout.html' %}

{% block content %}
<main class="container">
    <div class="card mt-5">
        <div class="card-header">
            <h1>Cerrar sesión?</h1>
        </div>
        <div class="card-body">
            <h2>Hay una sesión activa</h2>
            <form action="{% url 'usuarios:logout_user' %}?next={{next}}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="next" value="{{next}}">
                <p>¿Desea cerrar sesión?</p>
                <button class="btn btn-danger" type="submit">Cerrar sesion</button>
                <a class="btn btn-secondary" href="{{next}}">Cancerlar</a>
            </form>
        </div>
    </div>
</main>
{% endblock  %}

Desafio-13/templates/data/data_user/login.html
{% extends 'layout.html' %}

{% load crispy_forms_tags %}

{% block content %}
<main class="container">
    <form action="" method="POST">
        <h1 class="mt-5">Iniciar Sesión</h1>
        {% csrf_token %}
        <input type="hidden" name="next" value="{{next}}">
        {{form|crispy}}
        <button class="btn btn-success" type="submit">Iniciar sesion</button>
        <a href="{% url 'usuarios:signup_user' %}?next={{next}}">Crear nueva cuenta</a>
        <a href="{% url 'usuarios:password_reset' %}">¿Olvidaste tu contraseña?</a>
    </form>
</main>
{% endblock  %}

Desafio-13/templates/data/data_user/password_reset_complete.html
{% extends 'layout.html' %}

{% block content %}
<main class="container">
    <h1>Contraseña restablecida</h1>
    <p>Tu contraseña ha sido restablecida con éxito. Ahora puedes iniciar sesión con tu nueva contraseña.</p>
    <a href="{% url 'usuarios:login_user' %}">Iniciar sesión</a>
</main>
{% endblock %}

Desafio-13/templates/data/data_user/password_reset_confirm.html
{% extends 'layout.html' %}

{% load crispy_forms_tags %}

{% block content %}
<main class="container">
    <form method="post">
        {% csrf_token %}
        <h1>Restablecer contraseña</h1>
        <p>Por favor, ingresa tu nueva contraseña a continuación.</p>
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Guardar nueva contraseña</button>
    </form>
</main>
{% endblock %}

Desafio-13/templates/data/data_user/password_reset_done.html
{% extends 'layout.html' %}

{% block content %}
<main class="container">
    <h1>Correo enviado</h1>
    <p>Hemos enviado un correo electrónico con instrucciones para restablecer tu contraseña. Por favor, revisa tu bandeja de entrada.</p>
</main>
{% endblock %}

Desafio-13/templates/data/data_user/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}

{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'usuarios:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}

{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

Desafio-13/templates/data/data_user/password_reset_form.html
{% extends 'layout.html' %}

{% load crispy_forms_tags %}

{% block content %}
<main class="container">
    <form method="post">
        {% csrf_token %}
        <h1>Restablecer contraseña</h1>
        <p>Por favor, introduce tu dirección de correo electrónico para restablecer tu contraseña.</p>
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Enviar correo de restablecimiento de contraseña</button>
    </form>
</main>
{% endblock %}

Desafio-13/templates/data/data_user/signup.html
{% extends 'layout.html' %}

{% load crispy_forms_tags %}

{% block content %}
<main class="container">
    <form action="" method="POST">
        <h1 class="mt-5">Registro</h1>
        {% csrf_token %}
        <input type="hidden" name="next" value="{{next}}">
        {{form|crispy}}
        <p>
            <button class="btn btn-success" type="submit">Registrarse</button>
            <a href="{% url 'usuarios:login_user' %}?next={{next}}">Iniciar sesion</a>
        </p>
    </form>
</main>
{% endblock  %}