Desafio-13/articulo/urls.py
from django.urls import path
from .views import  ArtCreateView, AllArticlesView, AllCategoriaView,AllCategoriaArticlesView, CategoryCreateView, CategoryDeleteView, ArtDetailView, ArtUpdateView, ArtDeleteView, AllAboutView, AllContactView

app_name="articulos"

urlpatterns = [

    path('create/', ArtCreateView.as_view(), name="article_create"),

    path('all-articles/', AllArticlesView.as_view(), name="all_articles"),

    path('all-category/', AllCategoriaView.as_view(), name="all_category"),

    path('category/<int:category_id>/', AllCategoriaArticlesView.as_view(), name='all_category_articles'),

    path('create-category/', CategoryCreateView.as_view(), name="create_category"),

    path('<int:pk>/delete-category/', CategoryDeleteView.as_view(), name="delete_category"),

    path('Article/<int:post_id>/', ArtDetailView.as_view(), name="detail_article"),

    path('<int:pk>/update/', ArtUpdateView.as_view(), name="update_article"),

    path('<int:pk>/delete-article/', ArtDeleteView.as_view(), name="delete_article"),

    path('about/', AllAboutView.as_view(), name="about"),

    path('contac/', AllContactView.as_view(), name="contact")
]

Desafio-13/comentarios/urls.py
from django.urls import path
from .views import CommentUpdateView, CommentDeleteView

app_name = 'comentarios'

urlpatterns = [
    path('editar/<int:comment_id>/', CommentUpdateView.as_view(), name='update_comment'),
    path('eliminar/<int:comment_id>/', CommentDeleteView.as_view(), name='delete_comment'),
]

Desafio-13/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from .views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name="home"),
    path('accounts/', include('usuarios.urls')),
    path('articles/', include('articulo.urls')),
    path('comentarios/', include('comentarios.urls')),
    path('contacto/', include('contacto.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Desafio-13/usuarios/urls.py
from .views import CustomPasswordResetView, CustomPasswordResetDoneView, CustomPasswordResetConfirmView, CustomPasswordResetCompleteView
from django.urls import path
from .views import *
from . import views

app_name="usuarios"

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login_user'), 
    path('signup/', CustomRegisterUserView.as_view(), {'next_page': None}, name='signup_user'),  
    path('logout/', CustomLogoutView.as_view(), name='logout_user'),  
    path('confirm_logout/', CustomConfirmLogoutView.as_view(), {'next_page': None}, name='confirm_logout_user'),

    path('author/<int:pk>/', views.AuthorDetailView.as_view(), name='author_detail'),

    path('update/', CustomUpdateUserView.as_view(), name='update_user'),
    path('change_password/', CustomPasswordChangeView.as_view(), name='change_password'),

    path('password_reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

Desafio-13/templates/Articulos/profile/articles/Art_create.html
{% extends 'layout.html' %}

{% block content %}
{% if user.is_authenticated and user.is_colaborador %}
    <h1>Crear Artículo</h1>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Guardar Artículo</button>
    </form>
    <br>
    <form method="get" action="{% url 'articulos:create_category' %}" enctype="multipart/form-data">
      {% csrf_token %}
      <button type="submit" class="btn btn-success">Crear Categoría</button>
    </form>
  {% else %}
    <p>Esta página solo está disponible para colaboradores. Por favor, inicia sesión o regístrate como colaborador.</p>
    <p><a href="{% url 'usuarios:login_user' %}">Iniciar sesión</a> | <a href="{% url 'usuarios:signup_user' %}">Registrarse</a></p>
{% endif %}
{% endblock %}

Desafio-13/templates/Articulos/profile/articles/Art_delete.html
{% extends 'layout.html' %}

{% block content %}
  <h1>Eliminar Artículo</h1>
  <p>¿Estás seguro de que deseas eliminar el siguiente artículo?</p>
  <h2>{{ article.title }}</h2>
  <p>{{ article.content }}</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit">Eliminar</button>
  </form>
{% endblock %}

Desafio-13/templates/Articulos/profile/articles/Art_detail.html
{% extends 'layout.html' %}

{% block content %}

{% if messages %}
    {% for message in messages %}
        {% if message.tags == 'success' %}
            <div class="alert alert-success" role="alert">
                <h4 class="alert-heading">¡Bien hecho!</h4>
                <p>{{ message }}</p>
                <hr>
                <p class="mb-0">¡Excelente trabajo!</p>
            </div>
        {% endif %}
    {% endfor %}
{% endif %}

<div class="container text-center mt-4">
    <h1>{{ article.title }}</h1>
    <h5 class="text-muted fs-6 card-title">{{ article.category }}</h5>
    <h2 class="my-2 h5 text-muted">{{ article.date_published }}</h2>
    <p>Author: <a href="{% url 'usuarios:author_detail' article.author.id %}">{{ article.author.username }}</a></p>
    <img src="{{ article.image.url }}" alt="{{ article.title }}" class="img-fluid my-4 w-50">
    <div class="my-4">
        {{ article.content|safe }}
    </div>

    {% if user.is_authenticated %}
        <div class="card bg-light p-4 mb-4">
            <h3 class="mb-3">Deja un comentario:</h3>
            <form method="post" class="form-inline justify-content-center">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary mx-2">Comentar</button>
            </form>
        </div>
    {% else %}
        <p class="mb-4">Inicia sesión para dejar un comentario.</p>
    {% endif %}

    {% if comments %}
    <div class="card bg-light p-4">
        <h3 class="mb-3">Comentarios:</h3>
        <ul class="list-unstyled">
            {% for comment in comments %}
            <li class="mb-3">
                <img src="{{ comment.author.image.url }}" alt="{{ comment.author.username }}" class="rounded-circle" width="40" height="40">
                <strong>{{ comment.author.username }}</strong> - {{ comment.created_at|date:"M d Y H:i" }}<br>
                {{ comment.content }}
    
                {% if user.is_authenticated %}
                    {% if user.is_colaborador or user == comment.author %}
                        <!-- Mostrar el botón de editar solo para el autor del comentario -->
                        {% if user == comment.author %}
                            <a href="{% url 'comentarios:update_comment' comment.id %}" class="btn btn-warning">Editar</a>
                        {% endif %}
    
                        <!-- Mostrar el botón de eliminar para el autor del comentario y colaboradores -->
                        <a href="{% url 'comentarios:delete_comment' comment.id %}" class="btn btn-danger">Eliminar</a>
                    {% endif %}
                {% endif %}
            </li>
            {% endfor %}
        </ul>
    </div>
    {% else %}
    <p class="mb-4">No hay comentarios todavía.</p>
    {% endif %}
    


{% endblock %}

Desafio-13/templates/Articulos/profile/articles/Art_list.html
{% comment %} {% extends 'layout.html' %}

{% block content %}
    <h1>Listado de Artículos</h1>

    <ul>
        {% for article in articles %}
            <li>
                <h2>{{ article.title }}</h2>
                <p>{{ article.content }}</p>
                <!-- Agrega más detalles o campos del artículo aquí, si es necesario -->
            </li>
        {% endfor %}
    </ul>
{% endblock %} {% endcomment %}

{% extends 'layout.html' %}

{% block content %}
  <h1>Listado de Artículos</h1>
  <ul>
    {% for article in articles %}
      <li>
        <h2><a href="{% url 'blog:detail' article.pk %}">{{ article.title }}</a></h2>
        <p>{{ article.content }}</p>
        <!-- Agrega más detalles o campos del artículo aquí, si es necesario -->
      </li>
    {% endfor %}
  </ul>
{% endblock %}

Desafio-13/templates/Articulos/profile/articles/Art_update.html
{% extends 'layout.html' %}

{% block content %}
  <h1>Actualizar Artículo</h1>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Guardar Cambios</button>
  </form>
{% endblock %}

Desafio-13/templates/Articulos/profile/articles/all_articles.html
{% extends 'layout.html' %}
{% load static %}
{% block content %}
<div class="text-center">
    <h3 class="text-decoration-underline" class="font-monospace" >Listado de todos los Artículos</h3>
    <div class="row row-cols-1 row-cols-md-3 g-4">
        {% for article in page %}
        <div class="col">
            <!-- Agregar un estilo de fondo a la tarjeta -->
            <div class="card h-100 bg-secondary">
                <img src="{{ article.image.url }}" class="card-img-top" alt="{{ article.title }}" style="max-height: 150px; object-fit: cover;">
                <div class="card-body">
                    <h6 class="card-subtitle mb-2 text-muted">{{ article.date_published|date:'M d Y' }}</h6>
                    <h5 class="text-dark card-title">{{ article.title }}</h5>
                    {% if user.is_authenticated %}
                    <p>Author: {{ article.author.username }}</p>
                    {% endif %}
                    <h5 class="text-dark fs-6 card-title">{{ article.category }}</h5>
                    <p class="text-dark card-text">{{ article.content|striptags|truncatechars:100 }}</p>
                    {% if user.is_authenticated %}
                        <div class="btn-group" role="group" aria-label="Basic mixed styles example">
                            <a href="{% url 'articulos:detail_article' article.id %}" class="btn btn-success">Seguir Leyendo</a>
                            {% if user.is_colaborador %}
                            <a href="{% url 'articulos:update_article' article.id %}" class="btn btn-warning ms-2">Editar</a>
                            <a href="{% url 'articulos:delete_article' article.id %}" class="btn btn-danger ms-2">Eliminar</a>
                            {% endif %}
                        </div>
                    {% else %}
                            <a href="{% url 'articulos:detail_article' article.id %}" class="btn btn-success">Seguir Leyendo</a>
                    {% endif %}    
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>


<div class="container mt-4 articles-container">
    <!-- Contenedor para los artículos -->
    <div class="row row-cols-1 row-cols-md-3 g-4">
        {% for article in articles %}
        <!-- Tarjeta de artículo -->
        <div class="col">
            <!-- Agregar un estilo de fondo a la tarjeta -->
            <div class="card h-100 bg-dark">
                <!-- Contenido de la tarjeta -->
                <!-- ... (resto del contenido de la tarjeta) ... -->
            </div>
        </div>
        {% endfor %}
    </div>

    <!-- Mostrar enlaces de paginación -->
    <div class="pagination-container">
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center">
                {% if page.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page=1">&laquo; Anterior</a></li>
                    <li class="page-item"><a class="page-link" href="?page={{ page.previous_page_number }}">Anterior</a></li>
                {% endif %}

                <li class="page-item disabled"><span class="page-link">Página {{ page.number }} de {{ page.paginator.num_pages }}.</span></li>

                {% if page.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{ page.next_page_number }}">Siguiente</a></li>
                    <li class="page-item"><a class="page-link" href="?page={{ page.paginator.num_pages }}">Última &raquo;</a></li>
                {% endif %}
            </ul>
        </nav>
    </div>
</div>


{% endblock %}